apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: project4-anomaly-api
  namespace: project4-ml
  labels:
    app.kubernetes.io/name: project4-anomaly-api
    app.kubernetes.io/part-of: project4-ml-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project4-anomaly-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
