apiVersion: v1
kind: Namespace
metadata:
  name: project4-ml
  labels:
    app.kubernetes.io/name: project4-anomaly-detection
    app.kubernetes.io/part-of: project4-ml-platform
    app.kubernetes.io/managed-by: kubectl
